Revert "Feedback"
Steamledge-Pythoneers/phase-2-assignment-1-sti-x pull request #2
Opened 2020-09-29 06:12 UTC by sti-x

Reverts Steamledge-Pythoneers/phase-2-assignment-1-sti-x#1

2020-09-30 12:03 UTC, drak00 requested changes
**Note**
After your unauthorized merge I reverted to a new branch for you (revert-1-master) this is now the branch I'll be grading.

Your new branch (revert-1-master) fails the unit tests. 
ensure they pass all unit tests (Example/ folder and Exercise/ folder)

2020-10-01 14:02 UTC, drak00 commented on Exercise/compute_lowest_terms.py
> +	"""
only use this for docstrings. comments use #

2020-10-01 14:02 UTC, drak00 commented on Exercise/compute_lowest_terms.py
> +	"""
not a comment

2020-10-01 14:03 UTC, drak00 commented on Exercise/compute_lowest_terms.py
> +	"""
change to comment

2020-10-01 14:05 UTC, drak00 requested changes
fails Example/ folder unit test

fails Exercise/ folder unit test

add 'gothca' unit test from slack

2020-10-01 21:36 UTC, sti-x commented
I hope it works this time, made another push

2020-10-01 22:02 UTC, drak00 approved these changes
Great! though you didn't add the gotcha test function, It passed when I added it locally.
Also one of your commits was not in imperative voice. I'll let that slide this once, remember to always use 
imperative tone for commit messages in the future.

2020-10-01 22:03 UTC, merged

2020-10-02 00:50 UTC, sti-x commented
Noted Boss, thank you for being so patient with me during this learning process.

2020-10-02 09:48 UTC, drak00 commented
We were all there at some point, never give up and you'll master all these in no time. All the best